# Project information
site_name: 'LUG @ USTC'
site_description: 'Documentation for LUG service maintenance'
site_author: 'USTC Linux User Group'
site_url: 'https://docs.ustclug.org/'

# Repository
repo_name: 'ustclug/documentations'
repo_url: 'https://github.com/ustclug/documentations'

# Copyright
copyright: 'Copyright &copy; 2020 USTC Linux User Group'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'teal'
    accent: 'teal'

# Customization
extra:
  social:
    - type: 'globe'
      link: 'https://lug.ustc.edu.cn/'
    - type: 'github'
      link: 'https://github.com/ustclug'

extra_javascript:
  - assets/js/extra.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Workflow:
    - Mirrors maintenance: 'workflow/mirrors/maintenance.md'
    - New VM in vSphere: 'workflow/vSphere/new_vm.md'
  - Infrastructure:
    - Intranet:
      - Overview: 'infrastructure/intranet/intranet.md'
      - Tinc: 'infrastructure/tinc/tinc.md'
      - LUGI VPN: 'infrastructure/intranet/lugivpn.md'
    - Servers Unified Authentication (LDAP): 'infrastructure/sua/sua.md'
    - SSH Certificate Authentication: 'infrastructure/sshca/sshca.md'
    - vSphere Cluster:
      - ESXi: '#'
      - vCenter: '#'
      - NFS: '#'
      - VDP: '#'
    - SaltStack: '#'
    - Backup: '#'
    - Monitor: 'infrastructure/monitor/monitor.md'
    - PPA: '#'
    - Google Apps / G Suite: '#'
    - Mail Agent: '#'
  - Services:
    - Mirrors:
      - History: 'services/mirrors/mirrors.md'
      - Hardware: 'services/mirrors/hardware.md'
      - Remote KVM: '#'
      - ZFS: 'services/mirrors/zfs.md'
      - HTTP Service: '#'
      - RSYNC Service: '#'
      - FTP Service: '#'
      - Reverse Proxy: '#'
      - Limiter: 'services/mirrors/limiter.md'
      - Repo sync: '#'
      - Mail list: 'services/mirrors/mail-list.md'
    - Blog: 'services/blog/blog.md'
    - Authoritative DNS: 'services/auth-dns/auth-dns.md'
    - Neat DNS: '#'
    - GitLab: '#'
    - DokuWiki: '#'
    - LUG VPN:
      - RADIUS: '#'
      - VPN: '#'
      - Web: '#'
    - Light: 'services/light/light.md'
    - PXE:
      - LIIMS: 'services/pxe/liims.md'
    - Telegram Web: 'services/telegram-web/telegram-web.md'
    - FTP: 'services/ftp/ftp.md'
    - USTC Life: 'services/ustc-life/ustc-life.md'
    - Generate 204: 'services/generate-204/generate-204.md'
    - Discontinued Services: 'services/discontinued/discontinued.md'
