# Project information
site_name: 'LUG @ USTC'
site_description: 'Documentation for LUG service maintenance'
site_author: 'USTC Linux User Group'
site_url: 'https://docs.ustclug.org/'

# Repository
repo_name: 'ustclug/documentations'
repo_url: 'https://github.com/ustclug/documentations'

# Copyright
copyright: 'Copyright &copy; 2003-2020 USTC Linux User Group. <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a>.'

# Configuration
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'teal'
    accent: 'teal'
  icon:
    logo: fontawesome/brands/linux
    repo: octicons/mark-github
  features: [tabs]

# Customization
extra:
  social:
    - icon: octicons/globe
      link: 'https://lug.ustc.edu.cn/'
    - icon: octicons/mark-github
      link: 'https://github.com/ustclug'

extra_javascript:
  - assets/js/extra.js

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - footnotes
  - markdown.extensions.def_list
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Main:
    - Index: index.md
    - Workflow:
      - Mirrors maintenance: 'workflow/mirrors/maintenance.md'
      - New VM in vSphere: 'workflow/vSphere/new-vm.md'
      - Add New User in LDAP: 'workflow/ldap/add-new-user.md'
    - Infrastructure:
      - Intranet:
        - Overview: 'infrastructure/intranet/intranet.md'
        - Tinc: 'infrastructure/tinc.md'
        - LUGI VPN: 'infrastructure/intranet/lugivpn.md'
      - Servers Unified Authentication (LDAP): 'infrastructure/ldap.md'
      - SSH Certificate Authority: 'infrastructure/sshca.md'
      - DNS: 'infrastructure/dns.md'
      - vSphere Cluster:
        - ESXi: '#'
        - vCenter: '#'
        - NFS: '#'
        - VDP: '#'
      - SaltStack: '#'
      - Backup: '#'
      - Monitor: 'infrastructure/monitor.md'
      - PPA: '#'
      - Google Apps / G Suite: 'infrastructure/google.md'
      - GitHub: infrastructure/github.md
      - Mail Agent: '#'
    - Services:
      - Mirrors:
        - History: services/mirrors/index.md
        - Current: services/mirrors/2/index.md
        - Auxiliary: services/mirrors/3/index.md
        - Staging:
          - Overview: services/mirrors/4/index.md
          - Volumes: services/mirrors/4/volumes.md
          - Networking:
            - Interfaces: services/mirrors/4/networking/index.md
          - Repositories: services/mirrors/4/repos.md
        - Server 1: services/mirrors/1/index.md
        - Hardware: 'services/mirrors/hardware.md'
        - Docker: 'services/mirrors/docker.md'
        - IPMI: '#'
        - ZFS: 'services/mirrors/zfs.md'
        - HTTP Service: '#'
        - RSYNC Service: '#'
        - FTP Service: '#'
        - Reverse Proxy: '#'
        - Limiter: 'services/mirrors/limiter.md'
        - Repo sync: '#'
        - Mail list: 'services/mirrors/mail-list.md'
      - Authoritative DNS: 'services/auth-dns.md'
      - Docker2: 'services/docker2.md'
      - Neat DNS: '#'
      - GitLab: 'services/gitlab.md'
      - DokuWiki: '#'
      - LUG VPN:
        - RADIUS: '#'
        - VPN: '#'
        - Web: '#'
      - Light: 'services/light.md'
      - PXE:
        - LIIMS: 'services/pxe/liims.md'
      - FTP: 'services/ftp.md'
      - Generate 204: 'services/generate-204.md'
      - Discontinued Services: 'services/discontinued.md'
    - Common Issues:
      - DNS: faq/dns.md
  - Projects:
    - Linux 101: projects/linux101/index.md
