name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: "v0.3.5"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: Install mdBook
      run: curl -sSL https://github.com/rust-lang/mdBook/releases/download/${MDBOOK_VERSION}/mdBook-${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | sudo tar -C /usr/local/bin zxf -
    - name: Build book
      run: mdbook build
    - name: Deploy to GitHub Pages
      run: |
        cd book
        git init --quiet
        git config user.name "GitHub"
        git config user.email "noreply@github.com"
        echo -n "docs.ustclug.org" > CNAME
        git add --all
        git commit --message "Auto deploy from GitHub Actions"
        git push https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/$GITHUB_REPOSITORY.git +HEAD:gh-pages
